from enum import Enum, auto

# Extensions Enum
class Ext(Enum):
    # Images
    PNG = auto()
    JPG = auto()
    JPEG = auto()
    GIF = auto()
    BMP = auto()
    TIFF = auto()
    TIF = auto()
    ICO = auto()
    SVG = auto()
    WEBP = auto()

    # Videos
    MP4 = auto()
    WEBM = auto()
    OGG = auto()
    AVI = auto()
    FLV = auto()
    MOV = auto()
    WMV = auto()
    MKV = auto()
    MPG = auto()
    M4V = auto()

    # Audio
    MP3 = auto()
    WAV = auto()
    FLAC = auto()
    AAC = auto()
    WMA = auto()
    AIFF = auto()
    ALAC = auto()
    APE = auto()
    DSD = auto()
    M4A = auto()

    # Documents
    PDF = auto()
    DOC = auto()
    DOCX = auto()
    XLS = auto()
    XLSX = auto()
    PPT = auto()
    PPTX = auto()
    ODT = auto()
    ODS = auto()
    ODP = auto()
    RTF = auto()
    TXT = auto()
    CSV = auto()
    MD = auto()
    MARKDOWN = auto()

    # Archives
    ZIP = auto()
    RAR = auto()
    TAR = auto()
    GZ = auto()
    BZ2 = auto()
    Z = auto()
    SEVENZ = auto()
    DMG = auto()
    ISO = auto()
    VHD = auto()
    VMDK = auto()

    # Executables
    EXE = auto()
    MSI = auto()
    SH = auto()
    BAT = auto()
    PS1 = auto()
    APPIMAGE = auto()

    # Fonts
    TTF = auto()
    OTF = auto()
    WOFF = auto()
    WOFF2 = auto()
    EOT = auto()

    # Programming
    PY = auto()
    JS = auto()
    JAVA = auto()
    CLASS = auto()
    JAR = auto()
    WAR = auto()
    EAR = auto()
    JSP = auto()
    PHP = auto()
    HTML = auto()
    CSS = auto()
    SCSS = auto()
    LESS = auto()
    SQL = auto()
    NO_SQL = auto()
    JSON = auto()
    XML = auto()
    YML = auto()
    YAML = auto()
