from typing import TypedDict, Optional
from domain.filesystem.entities.document_collection import DocumentCollection

class ProjectPlanWorkflowState(TypedDict):
    """
    Workflow state for the project plan workflow.

    Fields:
      - copy_prompt: Boolean flag indicating if the generated prompt should be copied to the clipboard instead of invoking the LLM.
      - directory_tree: A text representation of the directory tree.
      - exclude_rules: The exclude pattern string.
      - file_collection: The file collection (DocumentCollection) loaded from the project.
      - goal: The project plan goal string.
      - include_rules: The include pattern string.
      - project_path: The absolute project path.
      - project_rules: The project-specific rules (from .k/rules.txt).
      - source_code: Source code.
      - user_stories: The structured user stories plan generated by the workflow.
    """
    copy_prompt: bool
    directory_tree: str
    exclude_rules: str
    file_collection: DocumentCollection
    goal: str
    include_override: str
    include_rules: str
    project_path: str
    project_rules: str
    source_code: str
    user_stories: Optional[dict]
    verbose: bool